- libraries/eosiolib/core/eosio/crypto_ext.hpp
`crypto_ext.hpp` defines  `capi_checksum256` for internal use. Unfortunately this conflicts with  `capi_checksum256` in `system.hpp`. The fix is to rename `capi_checksum256`  to `capi_checksum256_ext` in `crypto_ext.hpp`.
Resolve https://github.com/AntelopeIO/cdt/issues/29
> [3.0] fix duplicate definition of capi_checksum256

- docs/03_command-reference/cdt-cc.md
- docs/03_command-reference/cdt-cpp.md
- docs/03_command-reference/cdt-ld.md
- docs/05_features/10_return_values_from_actions.md
- docs/06_how-to-guides/20_authorization/how_to_restrict_access_to_an_action_by_user.md
- docs/06_how-to-guides/40_multi-index/how-to-define-a-primary-index.md
- docs/06_how-to-guides/40_multi-index/how-to-define-a-secondary-index.md
- docs/06_how-to-guides/40_multi-index/how-to-define-a-singleton.md
- docs/06_how-to-guides/40_multi-index/how-to-delete-data-from-a-multi-index-table.md
- docs/06_how-to-guides/40_multi-index/how-to-insert-data-into-a-multi-index-table.md
- docs/06_how-to-guides/40_multi-index/how-to-instantiate-a-multi-index-table.md
- docs/06_how-to-guides/40_multi-index/how-to-iterate-and-retrieve-a-multi_index-table-based-on-secondary-index.md
- docs/06_how-to-guides/40_multi-index/how-to-iterate-and-retrieve-a-multi_index-table.md
- docs/06_how-to-guides/40_multi-index/how-to-modify-data-in-a-multi-index-table.md
- docs/06_how-to-guides/50_how-to-create-and-use-action-wrappers.md
- docs/06_how-to-guides/60_how-to-return-values-from-actions.md
- docs/07_best-practices/02_naming-conventions.md
- docs/07_best-practices/03_resource-planning.md
- docs/07_best-practices/04_data-design-and-migration.md
- docs/07_best-practices/05_securing_your_contract.md
- docs/07_best-practices/08_abi/00_understanding-abi-files.md
- docs/07_best-practices/08_abi/01_abi-code-generator-attributes-explained.md
- docs/07_best-practices/11_debugging_a_smart_contract.md
- docs/08_troubleshooting/index.md
- docs/09_tutorials/02_abi-variants.md
- docs/09_tutorials/03_create-an-abi-file.md
Replace deprecated terms, e.g. block.one, b1, EOSIO, platform (with framework)
Fix broken links
Resolves https://github.com/AntelopeIO/cdt/issues/37
Resolves https://github.com/eosnetworkfoundation/devrel/issues/32
> [docs] Clean up 3.0: EOSIO to Antelope

- docs/03_command-reference/cdt-cc.md
- docs/03_command-reference/cdt-cpp.md
- docs/03_command-reference/cdt-ld.md
- docs/05_features/10_return_values_from_actions.md
- docs/06_how-to-guides/20_authorization/how_to_restrict_access_to_an_action_by_user.md
- docs/06_how-to-guides/40_multi-index/how-to-define-a-primary-index.md
- docs/06_how-to-guides/40_multi-index/how-to-define-a-secondary-index.md
- docs/06_how-to-guides/40_multi-index/how-to-define-a-singleton.md
- docs/06_how-to-guides/40_multi-index/how-to-delete-data-from-a-multi-index-table.md
- docs/06_how-to-guides/40_multi-index/how-to-insert-data-into-a-multi-index-table.md
- docs/06_how-to-guides/40_multi-index/how-to-instantiate-a-multi-index-table.md
- docs/06_how-to-guides/40_multi-index/how-to-iterate-and-retrieve-a-multi_index-table-based-on-secondary-index.md
- docs/06_how-to-guides/40_multi-index/how-to-iterate-and-retrieve-a-multi_index-table.md
- docs/06_how-to-guides/40_multi-index/how-to-modify-data-in-a-multi-index-table.md
- docs/06_how-to-guides/50_how-to-create-and-use-action-wrappers.md
- docs/06_how-to-guides/60_how-to-return-values-from-actions.md
- docs/07_best-practices/02_naming-conventions.md
- docs/07_best-practices/03_resource-planning.md
- docs/07_best-practices/04_data-design-and-migration.md
- docs/07_best-practices/05_securing_your_contract.md
- docs/07_best-practices/08_abi/00_understanding-abi-files.md
- docs/07_best-practices/08_abi/01_abi-code-generator-attributes-explained.md
- docs/07_best-practices/11_debugging_a_smart_contract.md
- docs/08_troubleshooting/index.md
- docs/09_tutorials/02_abi-variants.md
- docs/09_tutorials/03_create-an-abi-file.md
Replace deprecated terms, e.g. block.one, b1, EOSIO, platform (with framework)
Fix broken links
Resolves https://github.com/AntelopeIO/cdt/issues/37
Resolves https://github.com/eosnetworkfoundation/devrel/issues/32
> [docs] Clean up: EOSIO to Antelope

- tests/toolchain/abigen-pass/nested_container.abi
- tools/include/eosio/abigen.hpp
Resolve https://github.com/AntelopeIO/cdt/issues/34.
Please see https://github.com/AntelopeIO/cdt/issues/34 for detailed problem description and solution discussion.
Previously, `map` ABI was a pair of `key` and `value`. If a `pair`'s component types were the same as a `map`, depending on the order of map and pair definition, different ABIs for pair were generated.
For example, before the fix, `pair_int32_int64` were different depending on `my_map` was defined before or after `my_pair`:
```
std::map<int32_t, int64_t> my_map; 
std::pair<int32_t, int64_t> my_pair;
```
generates
```
{
"name": "pair_int32_int64",
"base": "",
"fields": [
{
"name": "key",
"type": "int32"
},
{
"name": "value",
"type": "int64"
}
]
},
...
[
{
"name": "my_map",
"type": "pair_int32_int64[]"
},
{
"name": "my_pair", …
```
> [3.0] fix inconsistency in ABI generated for map

- libraries/eosiolib/core/eosio/varint.hpp
- tests/unit/varint_tests.cpp
Resolve https://github.com/AntelopeIO/cdt/issues/13
Based on https://github.com/AntelopeIO/cdt/pull/14. Thanks @smlu. To conform to our practice, fix release branch and then merge the fix to main.
Add comprehensive unit test cases.
> [3.0] add constexpr support to varint types

- libraries/native/native/eosio/crt.hpp
- libraries/native/native/eosio/tester.hpp
- tests/CMakeLists.txt
- tests/unit/CMakeLists.txt
- tests/unit/crt_tests.cpp
Solving https://github.com/AntelopeIO/cdt/issues/12
Replaced char buffer with std::string. Initial capacity of string is set to 4096.
Using output_stream::push should no longer cause buffer overflow.
Added unit tests for overflow.
> Replaced char array in output_stream to std::string to avoid buffer overflow

- docs/05_features/50_crypto-extensions.md
Resolved https://github.com/AntelopeIO/cdt/issues/89
> add a new document explaining crypto extensions

- libraries/eosiolib/core/eosio/crypto_ext.hpp
When attempting to use the new `eosio/crypto_ext.hpp` in a smart contract on more than one location, the `wasm-ld` linker throws duplicate symbol error, after asking on developer chat, @spoonincode figured out we were missing `inline` declarations on the `blake2_f` helper function, this patch-set removes some unnecessary white space and adds two `inline` declarations.
Closes #110
> Resolve #110: Add missing inline declaration on blake2_f intrinsics helper

- libraries/eosiolib/capi/eosio/action.h
- libraries/eosiolib/contracts/eosio/action.hpp
- tests/integration/contracts.hpp.in
- tests/integration/get_code_hash_tests.cpp
- tests/unit/test_contracts/CMakeLists.txt
- tests/unit/test_contracts/capi/action.c
- tests/unit/test_contracts/get_code_hash_read.cpp
- tests/unit/test_contracts/get_code_hash_table.hpp
- tests/unit/test_contracts/get_code_hash_write.cpp
Implement the CDT API wrapper for `get_code_hash` intrinsic and add some testing
Added `get_code_hash` intrinsic to contracts' C and C++ APIs
> Resolve #88

- libraries/eosiolib/contracts/eosio/multi_index.hpp
- tests/integration/contracts.hpp.in
- tests/integration/name_pk_tests.cpp
- tests/unit/test_contracts/CMakeLists.txt
- tests/unit/test_contracts/explicit_nested_tests.cpp
- tests/unit/test_contracts/name_pk_tests.cpp
Resolve #97 -- Using a `name` as a primary key in a table is such a common use case that even the core contracts do it extensively. Adding first class support for this use case to the `multi_index` template is trivial, and allows contract code to be more expressive.
The `multi_index` API now supports usage of a `name` as a table primary key, and implicitly casts it down to an `int` for indexing.
> Resolve #97: Allow `name` typed primary keys

- tests/toolchain/abigen-pass/tagged_number_test.abi
- tests/toolchain/abigen-pass/tagged_number_test.cpp
- tests/toolchain/abigen-pass/tagged_number_test.json
- tools/include/eosio/gen.hpp
Resolve #99
In my contracts, I use several template arguments which are expressions which resolve to integral values (such as an `eosio::name`) but are not literal integer values. This works great in my contracts, but causes abigen to fail.
This PReq fixes abigen in such cases where a template argument is an expression that resolves to an integer, but isn't an integer literal.
> Resolve #99: Fix abigen with int expression template arguments

- libraries/eosiolib/core/eosio/datastream.hpp
- tests/unit/datastream_tests.cpp
Resolves https://github.com/AntelopeIO/cdt/issues/103
Fixes crash in cdt-cpp when using a std::basic_string<> in action wrapper
> Handle basic_string in datastream serializing/deserializing

- libraries/eosiolib/core/eosio/asset.hpp
- tests/unit/asset_tests.cpp
This change brings parity between `asset` and `extended_asset` for operators.
Closes #105.
Brief doxygen comments for some comparison operators were made more specific.
These `extended_asset` operators were added:
- `extended_asset& operator*=(int64_t)`
- `extended_asset operator*(const extended_asset&, int64_t)`
- `extended_asset operator*(int64_t, const extended_asset&)`
- `int64_t operator/(const extended_asset&, const extended_asset&)`
- `extended_asset& operator/=( int64_t )`
- `extended_asset operator/( const extended_asset&, int64_t )`
This is an addition only, so no existing code should be impacted.
extended_asset unit tests were updated for the new operators.
> Add extended_asset operators and unit tests.

- tools/cc/cdt-cpp.cpp.in
- tools/include/compiler_options.hpp.in
- tools/include/eosio/codegen.hpp
- tools/include/eosio/utils.hpp
This is a backport of EOSIO/eosio.cdt#968 / EOSIO/eosio.cdt#1070 that resolves EOSIO/eosio.cdt#742. 
> * Fix dependency file generation (-MD/-MMD) to hold the original source and not the generated temporary file.
> * Make temporary filenames unique to avoid races in parallel builds.
> Fix some issues when building EOSIO contracts

- tests/toolchain/abigen-pass/singleton_contract.abi
- tests/toolchain/abigen-pass/singleton_contract.cpp
- tests/toolchain/abigen-pass/singleton_contract.json
- tools/include/eosio/abigen.hpp
Resolves #93 
Incorrect abi was generated for singletons - wrong name was taken.
> Fix getting wrong name of the table for singleton

- docs/06_how-to-guides/20_authorization/how_to_restrict_access_to_an_action_by_user.md
- docs/06_how-to-guides/40_multi-index/how-to-define-a-primary-index.md
- docs/06_how-to-guides/40_multi-index/how-to-define-a-secondary-index.md
- docs/06_how-to-guides/40_multi-index/how-to-define-a-singleton.md
- docs/06_how-to-guides/40_multi-index/how-to-delete-data-from-a-multi-index-table.md
- docs/06_how-to-guides/40_multi-index/how-to-insert-data-into-a-multi-index-table.md
- docs/06_how-to-guides/40_multi-index/how-to-instantiate-a-multi-index-table.md
- docs/06_how-to-guides/40_multi-index/how-to-iterate-and-retrieve-a-multi_index-table-based-on-secondary-index.md
- docs/06_how-to-guides/40_multi-index/how-to-iterate-and-retrieve-a-multi_index-table.md
- docs/06_how-to-guides/40_multi-index/how-to-modify-data-in-a-multi-index-table.md
- docs/06_how-to-guides/50_how-to-create-and-use-action-wrappers.md
- docs/06_how-to-guides/60_how-to-return-values-from-actions.md
- docs/index.md
Partially resolves https://github.com/eosnetworkfoundation/devrel/issues/204
Merges PR https://github.com/AntelopeIO/cdt/pull/127 from `3.1` to `main`
No new content added, just fixes broken links.
> [3.1 -> main] Fix broken links in cdt repo

- .cicd/platforms/ubuntu18.Dockerfile
- .cicd/platforms/ubuntu20.Dockerfile
- .cicd/platforms/ubuntu22.Dockerfile
- .gitmodules
- CMakeLists.txt
- modules/InstallCDT.cmake
- scripts/generate_deb.sh
- scripts/generate_tarball.sh
- tools/CMakeLists.txt
- tools/external/CMakeLists.txt
https://github.com/AntelopeIO/cdt/issues/112
> add antler-proj to cdt

- .gitignore
Changed build ignore to from `build/*` to `[Bb]uild*/` to allow for example: `Build_debug/` and `build_release/` etc.
Added `CMakeLists.txt.user` to ignore QtCreator editor/debugger artifacts.
> Added additional build and editor files.

- libraries/eosiolib/contracts/eosio/multi_index.hpp
- libraries/meta_refl/include/bluegrass/meta/for_each.hpp
- tests/integration/contracts.hpp.in
- tests/integration/multi_index_tests.cpp
- tests/unit/test_contracts/CMakeLists.txt
- tests/unit/test_contracts/multi_index_tests.cpp
fixes #137 
Also I copied `multi_index` tests from leap as they have much more coverage than we have in cdt.
Note for reviewer:
new tests were added to `integration_tests`. Those tests require `leap` and we do not execute them by default as part of `Build & Test` steps. Please check those locally. All you need is to have a leap in your path so `find_package(leap)` would find it. The reason we need `leap` is testing utilities and primarily class `eosio::testing::tester` to load contracts, produce blocks, etc.
> multi_index bugfix after migration from boost + tests

- docs/08_troubleshooting/index.md
Add new troubleshooting section for backward incompatible change in acessing std::map from CDT 3.0.1
Resolves #90 
Explain differences in generating abi for std::map before and after CDT 3.0.0
Modified documentation in this PR
> Add new troubleshooting section for generating abi for maps

- tests/integration/action_results_test.cpp
- tests/integration/capi_tests.cpp
- tests/integration/codegen_tests.cpp
- tests/integration/crypto_tests.cpp
- tests/integration/get_code_hash_tests.cpp
- tests/integration/main.cpp
- tests/integration/memory_tests.cpp
- tests/integration/name_pk_tests.cpp
Fixes building cdt's tests with a libtester from leap's `main` branch (post 4.0.x branch)
> remove unused `Runtime.h` include now removed in libtester's main

- libraries/eosiolib/contracts/eosio/multi_index.hpp
- tests/unit/test_contracts/multi_index_tests.cpp
Resolves #135 
Add insert, remove and update methods to multi_index
For multi_index there are 3 new methods: insert (alias for emplace), remove (alias for erase), update (alias for modify).
If there is documentation for multi_index 3 new methods should be added. It might be in separate repo `docs`.
> Add insert, remove and update methods to multi_index (and index)

- tests/toolchain/abigen-pass/singleton_contract_simple.abi
- tests/toolchain/abigen-pass/singleton_contract_simple.cpp
- tests/toolchain/abigen-pass/singleton_contract_simple.json
- tools/include/eosio/abigen.hpp
> fixing abi for singleton with non-table type

- docs/05_features/50_crypto-extensions.md
The crypto API description was updated to make it more user friendly corresponding to issue https://github.com/AntelopeIO/cdt/issues/176
- [ x] Documentation Additions
> Proposal: Update description of the crypto API to make it more user friendly

- .cicd/platforms.json
- .cicd/platforms/ubuntu22-llvm.Dockerfile
- .github/workflows/build.yaml
- libraries/meta_refl/include/bluegrass/meta/function_traits.hpp
Relates to #192
Allows to compile CDT with clang-16.
I have added new Docker image with ubuntu22 & clang-16.
This is also related to #185 
Changes:
1. `get_types` seems to be unused
2. `parameters_from_impl` is used (indirectly) by `return_type_t`  - tests for it are in `traits_tests.cpp`.
> compile with clang-16

- libraries/eosiolib/core/eosio/datastream.hpp
Add additional explicit stream operator overloads for `basic_string<uint8_t>` as there is a bug that fails to match against `basic_string<T>`.
Resolves #190
> add explicit overloads

- libraries/meta_refl/modules/catch2_install.cmake.in
The version of catch2 in use is [old enough to fail compiles](https://github.com/catchorg/Catch2/issues/2421) on updated Linux operating systems. Update to latest version in v2.0 series to fix builds.
Ideally, it would be updated to the v3.0 series... but this fixes the build without code changes =)
- No API Changes
- No Documentation Additions
> [Meta-Refl] Update catch2 to v2.13.10

- .cicd/defaults.json
- .github/workflows/build.yaml
Make leap-dev download target configurable.
Use `defaults.json` to specify default location/target to attempt to download the `leap-dev` package from. Allow dynamic configuration through `workflow_dispatch` input in github.
Resolves: https://github.com/AntelopeIO/cdt/issues/216
For example:
The run here: [Manual Build & Test Run](https://github.com/AntelopeIO/cdt/actions/runs/6090349556) was manually dispatched from `cdt` branch `cicd-override-leap-dev-target` with the `Override leap-dev target` input set to `hotstuff_integration`.  This can be seen in the `Build & Test (ubuntu20)` output in the step `Download leap-dev.deb (Ubuntu20 only)`:
```
Run AntelopeIO/asset-artifact-download-action@v3
with:
owner: AntelopeIO
repo: leap
file: leap-dev.*(x86_64|amd64).deb
target: …
```
> Make leap-dev download target configurable.

- libraries/eosiolib/core/eosio/datastream.hpp
This merges up #191 to main.. which it appears never was months ago.
> [4.0 -> main] add explicit overloads

- tools/include/compiler_options.hpp.in
- tools/include/eosio/utils.hpp
When building cdt on macOS, it would error out about not being able to find the Foundation framework. This was because when cdt's ld driver was run with `-fnative` it didn't tell `ld` the system's SDK path.
The current SDK can be discovered via `xcrun --show-sdk-path`. I'm not sure any other way, so call off to that when creating the command line arguments to pass to `ld`. You can find something a little similar when cmake initializes its environment, so I'm not completely out of whack: https://github.com/Kitware/CMake/blob/123cdf981661c8ae32335d4ae7e1ddcbcffd09cc/Modules/Platform/Darwin-Initialize.cmake#L144
I also removed `-Bstatic` as that isn't accepted by macOS's linker any longer. afaict that is unneeded since `-static` will be passed anyways.
> [4.0] fix `-fnative` linking on macOS

- tests/toolchain/abigen-pass/singleton_contract.abi
- tests/toolchain/abigen-pass/singleton_contract.cpp
- tools/include/eosio/abigen.hpp
fixes #225 
after #201 we introduced a new logic where structure defined out of contract doesn't go to ABI.
There is an exception to that that is actively used by system contract. A lot of structures are defined out of contract but those have `[[eosio::contract("name")]]` tag. That case was added to exceptions and also search of contract class was improved as in some cases in `reference-contracts` it was not found the old way. Also a fix added where structure that was defined out of contract was not properly defined in structures. That is reflected in `singleton_contract.abi` and corresponding test.
> improve abi generation

- docs/roadmap.md
Resolves #205 
Add a roadmap for milestone 5, and start public discussion 
Noe
Add a roadmap for milestone 5, and start public discussion
> Roadmap Doc for public consumption 

- libraries/meta_refl/include/bluegrass/meta/function_traits.hpp
This `is_callable_v<>()` workaround causes build breakage on newer clang (such as latest two versions of Xcode). Fix is identical to AntelopeIO/eos-vm#4
Sending this to 4.0.x is a little debatable, but 4.0.x may live for quite some time so it's nice to get macOS build fully operational again.
> [4.0] remove `is_callable_v<>` workaround, fixing build on latest clang

- tools/include/compiler_options.hpp.in
- tools/include/eosio/utils.hpp
> [4.0 -> main] fix `-fnative` linking on macOS

- .github/workflows/release.yaml
Similar to leap's release workflow, I guess we'll just have to merge this and hope it works next time we do a release (and tweak accordingly) since I don't have a good way to clearly demonstrate that it works. I have tested it on a private repo though.
Resolves #243
> [4.0] on release, upload .deb as release asset automatically

- .github/workflows/release.yaml
main merge of #247
resolves #243
> [4.0 -> main] on release, upload .deb as release asset automatically

- libraries/eosiolib/core/eosio/check.hpp
- libraries/eosiolib/core/eosio/crypto_bls_ext.hpp
Return failure (-1) for `n==0` for `bls_g1_weighted_sum`, `bls_g2_weighted_sum`, and `bls_pairing`.
Added `return_code` enum for return code error codes for `bls` and `alt_bn128` and any others that use leap standard `return_code` enum.
See description.
See description.
Resolves #253
> Return -1 on n==0 for bls_g1_weighted_sum, bls_g2_weighted_sum, and bls_pairing

- libraries/eosiolib/contracts/eosio/instant_finality.hpp
- tests/integration/instant_finality_tests.cpp
- tests/unit/test_contracts/instant_finality_tests.cpp
Rename `finalizer_authority`, `finalizer_policy` types to match `eosio.bios` and `leap` names.
Depends on: https://github.com/AntelopeIO/leap/pull/2004 for tests.
- [ x ] API Changes
- [ x ] Documentation Additions
Resolves #257
> IF: Rename set_finalizers types to match `eosio.bios` and `leap` names

- libraries/eosiolib/contracts/eosio/multi_index.hpp
- tests/unit/test_contracts/multi_index_tests.cpp
Revert the following commits from main branch due to lack of testing, and not in any release. See issue #260 for issue and PR history. 
This update is the produce of the following command. 
`git revert 65f928f a1aae5f 2b0fd5c 94ca050`
Validated by comparing against pre-merge commit.
`git diff e77c18e74 libraries/eosiolib/contracts/eosio/multi_index.hpp`
`git diff e77c18e74 tests/unit/test_contracts/`
Running Build and Test on Branch Now
> Revert Alias of Multi-Index Operations

- .github/workflows/build.yaml
update `.github/workflow` to use ubuntu22 version of leap-dev for integration tests. Update actions to run against ubuntu22 version of CDT, previously ran against ubuntu20. 
Fixes #269
> Updated Build&Test to use ubuntu22 leap

- .github/workflows/build.yaml
- README.md
- libraries/eosiolib/base64.cpp
- libraries/eosiolib/contracts/eosio/multi_index.hpp
- libraries/eosiolib/core/eosio/base64.hpp
- libraries/eosiolib/core/eosio/crypto_bls_ext.hpp
- tests/integration/bls_tests.cpp
- tests/integration/instant_finality_tests.cpp
- tests/unit/base64_tests.cpp
- tests/unit/test_contracts/multi_index_tests.cpp
- tools/include/compiler_options.hpp.in
Update CDT to match Leap after https://github.com/AntelopeIO/leap/issues/2061.
* Update CDT Base64 library's base64 URL encoding/decoding to match Leap's.
* Change CDT BLS to use base64 URL encoding/decoding.
* Add new tests and adapt existing tests for base64 URL encoding/decoding.
Resolve https://github.com/AntelopeIO/cdt/issues/271 and https://github.com/AntelopeIO/cdt/issues/268.
> IF: Change BLS library to use Base64 URL encoding/decoding; update Base64 library to match Leap's

- libraries/eosiolib/core/eosio/crypto_bls_ext.hpp
Several functions in `crypto_bls_ext.hpp` miss inline specifier, causing duplicate symbol errors when the file is included by multiple files.
Resolved https://github.com/AntelopeIO/cdt/issues/274.
> IF: Add missing inline specifier to several methonds in crypto_bls_ext.hpp

- .cicd/defaults.json
- .github/workflows/build.yaml
- README.md
- docs/07_best-practices/08_abi/00_understanding-abi-files.md
- docs/09_tutorials/03_create-an-abi-file.md
- modules/TestsExternalProject.txt
- tests/CMakeLists.txt
- tests/integration/CMakeLists.txt
- tests/integration/multi_index_tests.cpp
- Update integration tests to use Spring instead of Leap
Resolves #276
> Use spring instead of leap for integration tests

- libraries/eosiolib/capi/eosio/instant_finality.h
- libraries/native/intrinsics.cpp
- tests/unit/test_contracts/capi/privileged.c
4.1 branched before #280 but this change is needed to get tests to actually pass. Add #280 change in to 4.1
> [4.1] pick from main: Update c interface of set_finalizers

- .github/workflows/build.yaml
The ubuntu22 package will work on 22+ but not 20. The ubuntu20 package will work on 20, 22, and 24. Unless we no longer support ubuntu20 we should be using that .deb instead.
> [4.1] upload ubuntu20 .deb package

- .cicd/platforms.json
- .cicd/platforms/ubuntu24.Dockerfile
- .github/workflows/build.yaml
With Ubuntu 24.04 released and the README stating
> Recent Ubuntu LTS releases are the only Linux distributions that we fully support
https://github.com/AntelopeIO/cdt/blob/0ab129eb93addcfcc6203f0bbed6d71351c9afb3/README.md?plain=1#L31
might as well make sure it's building/working on ubuntu 24 too.
> [4.1] add ubuntu 24.04 to CI

- .github/workflows/build.yaml
- CMakeLists.txt
main merge of #285
> The ubuntu22 package will work on 22+ but not 20. The ubuntu20 package will work on 20, 22, and 24. Unless we no longer support ubuntu20 we should be using that .deb instead
> [4.1 -> main] upload ubuntu20 .deb package

- README.md
The readme has version specific download links updating those links in release/4.1 branch. Separate PR merge into main.
> [4.1] updated artifact download links

- .cicd/defaults.json
- .github/workflows/build.yaml
- tests/integration/instant_finality_tests.cpp
spring's package name has been changed to `antelope-spring`, update dev package usage here accordingly
There appears to be some failure in `instant_finality_test` related to the change...
> [4.1] use `antelope-spring-dev.deb` instead of `spring-dev.deb`

- .cicd/defaults.json
- .github/workflows/build.yaml
- README.md
- tests/integration/instant_finality_tests.cpp
merges to main
* #282 
* #292
But also tacks on c250347 which effectively undoes much of #282 since the link in main's README ought to remain the most recent stable release until 4.1.0 is released.
I think going forward maybe we don't touch the URL in the release branch until the final (first non-rc) release. (the headache/confusion around this is exactly why I removed direct download links from leap/spring's README :innocent: )
> [4.1 -> main] use `antelope-spring-dev.deb` instead of `spring-dev.deb`; fix finality test

- libraries/eosiolib/contracts/eosio/singleton.hpp
Methods `exists`, `get` and `get_or_default` do not modify the state of singleton, so it seems reasonable to mark them as const.
> Marking appropriate methods of singleton as const

- tests/integration/instant_finality_tests.cpp
`instant_finality_extension` renamed to `finality_extension` in https://github.com/AntelopeIO/spring/pull/364
> instant_finality_extension renamed to finality_extension

- tests/integration/instant_finality_tests.cpp
`instant_finality_extension` renamed to `finality_extension` in https://github.com/AntelopeIO/spring/pull/364
Backport of #298
> [4.1] instant_finality_extension renamed to finality_extension

- docs/03_command-reference/cdt-cc.md
- docs/03_command-reference/cdt-cpp.md
- docs/03_command-reference/cdt-ld.md
- docs/man/cdt-cc.1.md
- docs/man/cdt-cpp.1.md
- docs/man/cdt-ld.1.md
- tests/unit/CMakeLists.txt
- tools/include/compiler_options.hpp.in
We've struggled with cdt generating slightly different outputs build-to-build. Typically the number of output permutations is low which allows eventually coming to a consensus between two independent build environments (e.g. two individuals building a contract) by just building over and over until matching up, but clearly this is not ideal behavior and may not always be the case.
The CFL Alias Analysis optimization looks to be the source of the build indeterminism. Disable it by default, and switch the exposed option to allow it to be reenabled in case someone out there really needs it, or finds some severe regression due to the removal of this optimization. (I'm tempted to just remove it entirely: LLVM 9 documents this optimization pass as experimental)
Technically this is a breaking …
> [4.1] disable CFL Alias Analysis by default; fixes known cases of indeterministic build output

- libraries/eosiolib/core/eosio/datastream.hpp
- tests/unit/datastream_tests.cpp
Fixes the issue that the target is not reset if the source does not have a value. The issue will cause mismatch of source and target if the target already has a value, as that value will be kept.
Resolves https://github.com/AntelopeIO/cdt/issues/334.
> Fix missing reset when deserializing std::optional if serialized value is empty

- .cicd/defaults.json
- libraries/eosiolib/core/eosio/bitset.hpp
- tests/integration/bitset_tests.cpp
- tests/unit/test_contracts/simple_tests.cpp
I mistakingly added a `throw` in `bitset.hpp` when copying code from spring.
> Should not use `throw` in contracts.

- .cicd/defaults.json
- libraries/eosiolib/contracts/eosio/action.hpp
- libraries/eosiolib/contracts/eosio/call.hpp
- libraries/eosiolib/contracts/eosio/detail.hpp
- tests/integration/call_tests.cpp
- tests/integration/contracts.hpp.in
- tests/toolchain/compile-fail/sync_call_params_num_tests.cpp
- tests/toolchain/compile-fail/sync_call_params_num_tests.json
- tests/toolchain/compile-fail/sync_call_params_type_tests.cpp
- tests/toolchain/compile-fail/sync_call_params_type_tests.json
- tests/unit/test_contracts/CMakeLists.txt
- tests/unit/test_contracts/sync_call_addr_book_callee.cpp
- tests/unit/test_contracts/sync_call_addr_book_callee.hpp
- tests/unit/test_contracts/sync_call_addr_book_caller.cpp
- tests/unit/test_contracts/sync_call_callee.cpp
- tests/unit/test_contracts/sync_call_callee.hpp
- tests/unit/test_contracts/sync_call_caller.cpp
- tests/unit/test_contracts/sync_call_not_supported.cpp
- tests/unit/test_contracts/sync_call_not_supported.hpp
- tools/include/eosio/codegen.hpp
This PR implements `call_wrapper` for contract authors to simplify making sync calls. Instead of using sync call host functions directly, it is recommend contract authors use `call_wrapper`.
Below is a full working example of caller contract making a sync call in the callee contract.
Calle header file "callee.hpp"
```
#include <eosio/call.hpp>
#include <eosio/eosio.hpp>
class [[eosio::contract]] callee : public eosio::contract{
public:
using contract::contract;
[[eosio::call]]
uint32_t sum(uint32_t a, uint32_t b, uint32_t c);
using sum_func           = eosio::call_wrapper<"sum"_n, &sync_call_callee::sum>;
using sum_func_read_only = eosio::call_wrapper<"sum"_n,
&sync_call_callee::sum,
access_mode::read_only>;
using sum_func_no_op     = eosio::call_wrapper<"sum"_n,
&sync_call_callee::sum, …
```
> SC: Implement call wrapper to simplify making sync calls

- libraries/eosiolib/contracts/eosio/call.hpp
- libraries/eosiolib/core/eosio/hash_id.hpp
- libraries/eosiolib/core/eosio/identifier.hpp
- tests/toolchain/abigen-pass/sync_call_test.abi
- tests/toolchain/compile-fail/sync_call_params_num_tests.cpp
- tests/toolchain/compile-fail/sync_call_params_type_tests.cpp
- tests/unit/test_contracts/sync_call_addr_book_callee.hpp
- tests/unit/test_contracts/sync_call_callee.cpp
- tests/unit/test_contracts/sync_call_callee.hpp
- tests/unit/test_contracts/sync_call_caller.cpp
- tests/unit/test_contracts/sync_call_not_supported.hpp
- tests/unit/test_contracts/sync_call_single_func.cpp
- tools/include/eosio/abi.hpp
- tools/include/eosio/abigen.hpp
- tools/include/eosio/codegen.hpp
- tools/include/eosio/utils.hpp
Work in progress:
This PR adds support of long sync call function names. Now a sync call function name can be any valid C++ identifier with max length of 128 characters. This provides much flexibilities in choosing sync call function names than using `eosio::name`.
Please note, this is a quick implementation for dev-preview-1. Internal implementation might be changed in dev-preview-2 but user-faced interface should keep the same.
Resolves https://github.com/AntelopeIO/cdt/issues/361
The following is a working example of using C++ identifiers for sync call function names.
```
#include <eosio/call.hpp>
#include <eosio/eosio.hpp>
struct struct1_t {
int64_t a;
uint64_t b;
};
struct struct2_t {
char a;
bool b;
int64_t c;
uint64_t d;
};
class [[eosio::contract]] sync_call_callee : public …
```
> SC: Support long sync call function names

- libraries/eosiolib/contracts/eosio/contract.hpp
- tests/integration/call_tests.cpp
- tests/toolchain/build-pass/separate_cpp_hpp.hpp
- tests/unit/test_contracts/sync_call_addr_book_callee.hpp
- tests/unit/test_contracts/sync_call_callee.cpp
- tests/unit/test_contracts/sync_call_callee.hpp
- tests/unit/test_contracts/sync_call_caller.cpp
- tools/include/eosio/codegen.hpp
Add `is_sync_call()` to `eosio::contract` class so users can use it together with `get_sender()` to perform basic authorization checks on sync calls (see https://github.com/AntelopeIO/cdt/issues/368 for an example).
It seems the current implementation of adding a default `is_call` argument to the constructor of `eosio::contract` is the cleanest one, except it imposes a restriction that if a new contract class contains sync calls and it provides its own constructor, the constructor's signature must match with `eosio::contract`'s, as in the example of https://github.com/AntelopeIO/cdt/commit/09b234bf35b99e84405a750de54608ae5802d2da
```cpp
class [[eosio::contract]] sync_call_addr_book_callee : public eosio::contract {
public:
sync_call_addr_book_callee(eosio::name receiver, eosio::name code, …
```
> [5.0.0-dev] Add `is_sync_call()` to `eosio::contract` class

- libraries/eosiolib/contracts/eosio/contract.hpp
- libraries/eosiolib/contracts/eosio/detail.hpp
- tests/integration/call_tests.cpp
- tests/integration/contracts.hpp.in
- tests/toolchain/build-pass/separate_cpp_hpp.hpp
- tests/unit/test_contracts/CMakeLists.txt
- tests/unit/test_contracts/sync_call_callee.cpp
- tests/unit/test_contracts/sync_call_callee.hpp
- tests/unit/test_contracts/sync_call_caller.cpp
- tests/unit/test_contracts/sync_call_cust_entry.cpp
- tools/include/eosio/codegen.hpp
Picking up changes from
https://github.com/AntelopeIO/cdt/pull/369
https://github.com/AntelopeIO/cdt/pull/373
https://github.com/AntelopeIO/cdt/pull/377
https://github.com/AntelopeIO/cdt/pull/379
> [main --> 5.0.0-dev1] Merge main to release/5.0.0-dev1
